dataset_params:
    train_im_sets: ["/Users/parteeksj/Desktop/VOCdevkit/VOC2007", "/Users/parteeksj/Desktop/VOCdevkit/VOC2012"]
    test_im_sets: ["/Users/parteeksj/Desktop/VOCdevkit/VOC2007-test"]
    num_classes: 20
    im_size: 448
    
model_params:
    im_channels: 3
    backbone_channels: 512
    conv_spatial_size: 7 # spatial size after all CONV layers.
    yolo_conv_channels: 1024 
    leaky_relu_slope: 0.1
    fc_dim: 4096
    fc_dropout: 0.5
    S: 7 # grid size
    B: 2 # number of bounding boxes per cell
    use_sigmoid: True
    use_conv: True
    
train_params:
    task_name: 'voc'
    seed: 1111
    acc_steps: 1
    log_steps: 100
    num_epochs: 135
    batch_size: 64
    lr_steps: [ 50, 75, 100, 125 ]
    lr: 0.001
    infer_conf_threshold : 0.2
    eval_conf_threshold : 0.001
    nms_threshold : 0.5
    ckpt_name: 'yolo_voc2007.pth'